settings:
        server_info:    { enabled: true, users: 1, ramp: 30, duration: 120, pt_delay: 12000, pt_range: 3000, delay: 0, loops: -1 }
        account_info:   { enabled: true, users: 1, ramp: 30, duration: 120, pt_delay: 12000, pt_range: 3000, delay: 0, loops: -1 }
        fee:            { enabled: true, users: 1, ramp: 30, duration: 120, pt_delay: 12000, pt_range: 3000, delay: 0, loops: -1 }
        ledger_current: { enabled: true, users: 1, ramp: 30, duration: 120, pt_delay: 12000, pt_range: 3000, delay: 0, loops: -1 }
        ledger_closed:  { enabled: true, users: 1, ramp: 30, duration: 120, pt_delay: 12000, pt_range: 3000, delay: 0, loops: -1 }
        nft_info:       { enabled: true, users: 1, ramp: 30, duration: 120, pt_delay: 12000, pt_range: 3000, delay: 0, loops: -1 }
        ledger_data:    { enabled: true, users: 1, ramp: 30, duration: 120, pt_delay: 12000, pt_range: 3000, delay: 0, loops: -1 }
        book_offers:    { enabled: true, users: 1, ramp: 30, duration: 120, pt_delay: 12000, pt_range: 3000, delay: 0, loops: -1 }
