settings:
        server_info:    { enabled:  true, users: 100, ramp: 360, duration:  720, pt_delay:    12, pt_range:    3, delay: 0, loops: -1 }
        server_state:   { enabled:  true, users:   2, ramp: 360, duration:  720, pt_delay:    12, pt_range:    3, delay: 0, loops: -1 }
        account_info:   { enabled:  true, users: 100, ramp: 360, duration:  720, pt_delay:    12, pt_range:    3, delay: 0, loops: -1 }
        fee:            { enabled:  true, users:   5, ramp: 360, duration:  720, pt_delay:    30, pt_range:    3, delay: 0, loops: -1 }
        ledger:         { enabled:  true, users: 100, ramp: 360, duration:  720, pt_delay:    60, pt_range:    6, delay: 0, loops: -1 }
        ledger_current: { enabled:  true, users:   5, ramp: 360, duration:  720, pt_delay:    60, pt_range:    6, delay: 0, loops: -1 }
        ledger_closed:  { enabled:  true, users:   5, ramp: 360, duration:  720, pt_delay:    60, pt_range:    6, delay: 0, loops: -1 }
        nft_info:       { enabled: false, users:   1, ramp: 360, duration:  720, pt_delay:   100, pt_range:   20, delay: 0, loops: -1 }
        ledger_data:    { enabled: false, users:   1, ramp: 360, duration:  720, pt_delay:   100, pt_range:   20, delay: 0, loops: -1 }
        book_offers:    { enabled:  true, users:  50, ramp: 360, duration:  720, pt_delay:    12, pt_range:    3, delay: 0, loops: -1 }
